### ISSUE TITLE
502 Bad Gateway on push to LHCI server

### ISSUE THREAD

**Issue by troydieter** [troydieter/lhci-fargate#15]
Currently investigating the following `502 Bad Gateway` response:

> Saved LHR to http://lhci.troydieter.com (a17953ee-1538-49be-b4f9-94f1ee75ef81)
> Saved LHR to http://lhci.troydieter.com (c8cbaec7-276f-4328-bef7-f245c617ac70)
> Saved LHR to http://lhci.troydieter.com (4a00748b-0744-4538-8c05-56c703a92fe1)
> Saved LHR to http://lhci.troydieter.com (6b4612a8-d68f-49cb-bd06-d9c150b02f3e)
> Saved LHR to http://lhci.troydieter.com (29870b62-d145-47b5-8782-9866a4cda9ae)
> Saved LHR to http://lhci.troydieter.com (5a99d53c-f84b-4bfd-b23d-853a15c49a78)
> Saved LHR to http://lhci.troydieter.com (70df412a-ae70-488a-9c63-09e0eae6c372)
> Saved LHR to http://lhci.troydieter.com (7cc3716a-fd54-45cb-b5f7-ecaf1de8fc21)
> Error: Unexpected status code 502
>   <html>
> <head><title>502 Bad Gateway</title></head>
> <body>
> <center><h1>502 Bad Gateway</h1></center>
> </body>
> </html>
> 
>     at ApiClient._convertFetchResponseToReturnValue (C:\Users\troy.dieter\AppData\Roaming\npm\node_modules\@lhci\cli\node_modules\@lhci\utils\src\api-client.js:79:21)
>     at runMicrotasks (<anonymous>)
>     at processTicksAndRejections (node:internal/process/task_queues:96:5)
>     at async runLHCITarget (C:\Users\troy.dieter\AppData\Roaming\npm\node_modules\@lhci\cli\src\upload\upload.js:452:3)        
>     at async Object.runCommand (C:\Users\troy.dieter\AppData\Roaming\npm\node_modules\@lhci\cli\src\upload\upload.js:589:16)   
>     at async run (C:\Users\troy.dieter\AppData\Roaming\npm\node_modules\@lhci\cli\src\cli.js:109:7)

**Comment by troydieter** [comment]
Resolved with latest #29
